services:
  - type: web
    name: task-flow-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input"
    startCommand: "gunicorn complice_taches.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: taskflowdb
    plan: free